spring:
  graphql:
    schema:
#      locations: classpath:graphql/lec01
#      locations: classpath:graphql/lec02
#      locations: classpath:graphql/lec03
      locations: classpath:graphql/lec04
    path: /graphql
    graphiql:
      enabled: true
      path: /graphiql
