spring:
  graphql:
    schema:
#      locations: classpath:graphql/lec01
#      locations: classpath:graphql/lec02
#      locations: classpath:graphql/lec03
#      locations: classpath:graphql/lec04
#      locations: classpath:graphql/lec05
#      locations: classpath:graphql/lec06
#      locations: classpath:graphql/lec07
#      locations: classpath:graphql/lec08
#      locations: classpath:graphql/lec09
#      locations: classpath:graphql/lec10
      locations: classpath:graphql/lec11
    path: /graphql
    graphiql:
      enabled: true
      path: /graphiql
